name: Git Sync

on: push

jobs:

  git-sync-tags-2-0:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:iqual-ch/pagedesigner_responsive_images.git"
          source_branch: "refs/tags/v2.0"                                          # <-- set source_branch to the "refs/tags/*" to mirror tags
          destination_repo: "git@git.drupal.org:project/pagedesigner_responsive_images.git"
          destination_branch: "refs/tags/2.0.0"                                     # <-- set destination_branch to the "refs/tags/*"
          ssh_private_key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
  
  git-sync-tags-2-1-1:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:iqual-ch/pagedesigner_responsive_images.git"
          source_branch: "refs/tags/2.1.1"                                          # <-- set source_branch to the "refs/tags/*" to mirror tags
          destination_repo: "git@git.drupal.org:project/pagedesigner_responsive_images.git"
          destination_branch: "refs/tags/2.1.1"                                     # <-- set destination_branch to the "refs/tags/*"
          ssh_private_key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
